apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofepapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dofepapp
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dofepapp
    spec:
      containers:
      - name: app-cont
        image: shekeriev/dofepapp:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dofepapp-svc
  labels:
    app: dofepapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: dofepapp
